### ISSUE TITLE
No such file or directory: 'cache/grid_batch.npy'

### ISSUE THREAD

**Issue by yaojinzhen** [BiDiff/bidiff#4]
Hi! Thanks for your excellent work.
When I tried to run the inference script, I encountered an error indicating that I did not have the file. How was this file generated?
The detailed error report is as follows:

```makefile
Traceback (most recent call last):
  File "/data1/user/bidiff/examples/bidiff/sample_bidiff.py", line 484, in <module>
    main(args)
  File "/home/user/miniconda3/envs/bidiff/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data1/user/bidiff/examples/bidiff/sample_bidiff.py", line 181, in main
    bidiff = BidiffModel.from_pretrained(args.ckpt_path, low_cpu_mem_usage=False, local_files_only=True)
  File "/data1/user/bidiff/src/diffusers/models/modeling_utils.py", line 698, in from_pretrained
    model = cls.from_config(config, **unused_kwargs)
  File "/data1/user/bidiff/src/diffusers/configuration_utils.py", line 234, in from_config
    model = cls(**init_dict)
  File "/data1/user/bidiff/src/diffusers/configuration_utils.py", line 613, in inner_init
    init(self, *args, **init_kwargs)
  File "/data1/user/bidiff/src/diffusers/models/bidiff.py", line 563, in __init__
    self.denoiser3d = denoiser3d_model(regress_rgb=regress_rgb,
  File "/data1/user/bidiff/src/diffusers/models/denoiser3d_rast.py", line 448, in __init__
    query_pts = np.load('cache/grid_batch.npy')
  File "/home/user/miniconda3/envs/bidiff/lib/python3.10/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'cache/grid_batch.npy'

```

**Comment by DingLihe** [comment]
Hi @yaojinzhen

Thanks for your interest in our work. The grid_batch file has been uploaded to Google Drive. 

Best,
Lihe
